spring:
  main:
   web-application-type: none
  shell:
   interactive:
    enabled: true	
  application:
    name: tasktracker
  datasource:
    url: jdbc:postgresql://localhost:5433/tasktracker
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

